# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
 - 3.1
 - oldrel
 - release
 - devel

before_install:
  - test $TRAVIS_R_VERSION_STRING = '3.1' && Rscript -e 'devtools::install_github("devtools")'

after_success:
  - Rscript -e 'covr::codecov()'
